version: '3'
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/var/www/html/.env
      - ./src:/var/www/html
      - ./logs:/var/log
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "8000:80"
    links:
      - db
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
    env_file:
      - .env
    networks:
      - app-network
  db:
    image: ${DB_IMAGE}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: foobar
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network
  vue:
    build: 
      context: .
      dockerfile: Dockerfile.vue
    volumes:
      - ./app:/app
    ports:
      - "8080:3001"
    links:
      - php
    depends_on:
      - php
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
